version: '3.7'
services:

  api-be:
    build: backend
    ports:
      - "${BACKEND_HOST_PORT}8000"
    volumes:
      - ./:/app
    working_dir: /app/backend
    stdin_open: true
    tty: true
    command: ${RUNSERVER:-uvicorn app.api:app --host 0.0.0.0}
    restart: ${DOCKER_RESTART:-no}
    networks:
      - backend-network

networks:
  backend-network:
